INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Historic Environment Scotland');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'HMRC');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Museum Galleries Scotland');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'OFGEM');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Scottish Government');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'South Ayrshire Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Transport Scotland');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'BFI');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Somerset County Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Chesterfield council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Derby');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Dorset LEP');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'AHDB');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Gateshead Council ');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Keele');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'The Trustees of the National Heritage Memorial Fund');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Dover');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'University of Newcastle');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Highlands & Islands Enterprise');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Enfield');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Oxfordshire County Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Welsh assembly government');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Northern Ireland');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'DEFRA');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'BEIS');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Invest NI');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Tourism NI');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Blaenau Gwent County Borough Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Scottish Enterprise');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Forestry Commission Scotland');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'MHCLG');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Gwynedd County Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Isle of Anglesey county council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Norfolk County Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Flintshire County council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Cumbria County Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Sheffield City Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Aberdeenshire Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Carmarthenshire County council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Northern Ireland Screen');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Hull City Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Gateshead Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Dumfries and Galloway council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Zero waste Scotland');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'DECC');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'North East Combined Authority');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Black Country Local Enterprise Partnership');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Suffolk county council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'GFirst Gloucestershire LEP');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Ceredigion County council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Government of Gibraltar');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Big Lottery Fund');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'The National Lottery Heritage Fund');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Homeless Link');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'WM5G');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'The School for Social Entrepreneurs');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Big Issue Invest Ltd');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Community Land & Finance CIC (T/A Resonance)');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Key Funds Investments Limited');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'The Foundation for Social Entrepreneurs (T/A UnLtd)');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'City Bridge Trust');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'DDCMS');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'DfT');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Liverpool');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'UKRI � Research Councils');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'UKRI � Innovate UK');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'SPRINT');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'UKGI');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Scottish Funding Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Arts Council England');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'VisitScotland');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Office for Civil Society');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'STFC');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'East Lancashire Chamber of Commerce');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Bradford Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Birmingham City Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'NOMENSA');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'UKSA');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Worcestershire');