CREATE UNIQUE INDEX award_num_not_null_idx ON award (AWARD_NUMBER)
WHERE AWARD_NUMBER IS NOT NULL;
CREATE UNIQUE INDEX ga_name_not_null_idx ON GRANTING_AUTHORITY (GA_NAME)
WHERE GA_NAME IS NOT NULL;
CREATE UNIQUE INDEX sc_number_not_null_idx ON SUBSIDY_MEASURE (SC_NUMBER)
WHERE SC_NUMBER IS NOT NULL;